react-component/image

examples/basic.tsx, src/Image.tsx, src/Preview.tsx, tests/__snapshots__/basic.test.tsx.snap, tests/preview.test.tsx
Fixes https://github.com/ant-design/ant-design/issues/26384
=> fix: stopPropagation

README.md, examples/basic.tsx, examples/controlled.tsx, src/Image.tsx, tests/controlled.test.tsx, tests/preview.test.tsx
Resolve https://github.com/ant-design/ant-design/issues/26664
=> feat: add previewVisible prop

assets/index.less, examples/basic.tsx, src/Image.tsx, src/PreviewGroup.tsx, tests/__snapshots__/controlled.test.tsx.snap, tests/controlled.test.tsx, tests/preview.test.tsx
=> feat: `preview` support `placeholder`

src/Image.tsx, src/PreviewGroup.tsx
close https://github.com/ant-design/ant-design/issues/28881
=> fix: Group src order not correct when src updated

src/PreviewGroup.tsx
Related https://github.com/react-component/image/pull/62#discussion_r560794305
=> chore: improve registerImage comment

README.md, src/Image.tsx, tests/fallback.test.tsx
=> Feat onerror

README.md, examples/controlledWithGroup.tsx, src/PreviewGroup.tsx, tests/__snapshots__/previewGroup.test.tsx.snap, tests/previewGroup.test.tsx
Fixes https://github.com/ant-design/ant-design/issues/29016
=> feat: support PreviewGroup controlled

src/Preview.tsx
Related https://github.com/ant-design/ant-design/issues/29156
https://user-images.githubusercontent.com/14831261/106557556-0a0e3800-655d-11eb-9f66-884381500e19.mp4
https://user-images.githubusercontent.com/14831261/106557573-12ff0980-655d-11eb-94c5-2bbef8c09b81.mp4
=> fix: drag moving offset value should be exclude window

tests/fallback.test.tsx
Related https://github.com/react-component/image/pull/67
=> test: mock trigger image error event

src/Image.tsx, src/Preview.tsx, src/PreviewGroup.tsx, tests/preview.test.tsx
Related https://github.com/ant-design/ant-design/pull/29268#issuecomment-775820284
=> feat: reset preview prop to Dialog

src/Image.tsx, tests/placeholder.test.tsx
=> fix: ensure placeholder is hidden

package.json, src/Image.tsx, src/Preview.tsx, src/PreviewGroup.tsx, tests/__snapshots__/preview.test.tsx.snap, tests/preview.test.tsx
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     add `rootClassName` api      |
| 🇨🇳 Chinese |     支持增加 `rootClassName`      |
⚠️ Please check all items below before review. ⚠️
=> feat: add rootClassName api

src/Image.tsx, tests/previewGroup.test.tsx
close https://github.com/ant-design/ant-design/issues/38112
=> fix(Image): should show error img in previewGroup

assets/index.less, package.json, src/Preview.tsx, tests/__snapshots__/controlled.test.tsx.snap, tests/__snapshots__/preview.test.tsx.snap, tests/__snapshots__/previewGroup.test.tsx.snap, tests/previewGroup.test.tsx
https://github.com/ant-design/ant-design/issues/36456
=> fix: Image preview motion

src/Preview.tsx, tests/__snapshots__/preview.test.tsx.snap
修复Modal中的Image点击预览操作条不显示
https://github.com/ant-design/ant-design/issues/38958#issuecomment-1326995687
=> fix: the operations getContainer default

package.json
add rc-motion to dependencies, to avoid phantom dependencies
close https://github.com/ant-design/ant-design/issues/39763
close https://github.com/react-component/image/issues/144
=> chore(deps): add rc-motion to dependencies

src/Image.tsx, src/Preview.tsx, tests/fallback.test.tsx
https://github.com/facebook/react/issues/15446#issuecomment-484699248
=> fix: fallback not working in ssr

src/Preview.tsx
remove never used afterClose and onChange in Preview.tsx
=> refactor(Preview): remove never used afterClose and onChange

src/Preview.tsx, src/hooks/useImageTransform.ts
=> style: fix typos

src/Preview.tsx, tests/previewGroup.test.tsx
fix https://github.com/ant-design/ant-design/issues/42693
=> fix: reset transform when switch

src/Image.tsx, src/Preview.tsx, src/PreviewGroup.tsx, tests/preview.test.tsx, tests/previewGroup.test.tsx
fix https://github.com/ant-design/ant-design/issues/42845
=> fix: pass img common props to preview img

README.md, src/Image.tsx, src/Preview.tsx, src/PreviewGroup.tsx
关闭后，能直接拖到桌面上得到一份文件。 https://github.com/ant-design/ant-design/issues/43753
=> feat: support movable

src/PreviewGroup.tsx
type: PreviewGroupPreview imageRender adding ImgInfo
=> type: PreviewGroupPreview imageRender adding ImgInfo
