react-component/image

package.json
src/Preview.tsx
tests/__snapshots__/basic.test.tsx.snap

close https://github.com/react-component/image/issues/24

fix: IDialogPropTypes import

---

package.json
src/Preview.tsx

升级 rc-dialog 到 8.3.x，rc-image 需要发一个 3.1.0，到 antd 的 feature 分支升级起来。
https://github.com/react-component/image/commit/51569b0dd59b5bc39889e17341437f9449b373b0

chore: upgrade rc-dialog to 8.3

---

README.md
src/Image.tsx
tests/__snapshots__/controlled.test.tsx.snap
tests/controlled.test.tsx

https://github.com/ant-design/ant-design/pull/26713#issuecomment-706511061

improve: preview props

---

src/Image.tsx
tests/__snapshots__/basic.test.tsx.snap
tests/basic.test.tsx

1. width and height should only be applied on img element
parent element will auto-scale
2. add imgStyle and imgClass
close [#26996](https://github.com/ant-design/ant-design/issues/26996)

fix: imgStyle and imgClass in Image Component

---

src/Preview.tsx
tests/preview.test.tsx

Listening to wheel event the determine the direction of the scrolling, and by that decide if zooming in or out.
This PR was opened due to this Feature Request in Ant Design repository's  issues: 
https://github.com/ant-design/ant-design/issues/28415
After this PR will be merged and a new version will be released I'll open a PR for Ant Design to integrate this new feature.

Added functionality for zoom in\out by sliding the wheel

---

examples/thumbnail.tsx
src/Image.tsx
tests/preview.test.tsx

Add `preview-src` to determine the original data.
```tsx
<Image
src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?x-oss-process=image/auto-orient,1/resize,p_10/quality,q_10"
preview={{
src: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
}}
/>;
```
Fixes https://github.com/react-component/image/pull/55
Fixes https://github.com/ant-design/ant-design/issues/28321

feat(Image): preview-src prop

---

src/Preview.tsx
tests/preview.test.tsx

预览图片在点击鼠标右键后，图片会跟随鼠标移动。🧐 图片拖拽应该只允许使用左键。

fix: only allow main button when drag image

---

src/Image.tsx
tests/placeholder.test.tsx

Fixes https://github.com/ant-design/ant-design/issues/28953

fix: recover deleted code

---

src/Image.tsx
tests/fallback.test.tsx

fix: https://github.com/ant-design/ant-design/issues/29112

fix(image): can't change image after set status to 'error'

---

src/Image.tsx
src/PreviewGroup.tsx
tests/preview.test.tsx

Fixes https://github.com/ant-design/ant-design/issues/29723

fix: PreviewGroup async src order

---

src/Preview.tsx
tests/previewGroup.test.tsx

[[English Template / 英文模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)]
| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |      When the picture is previewed, you can use the left and right arrow keys to switch    |
| 🇨🇳 中文 |     图片预览时, 可使用左右方向键进行切换     |
⚠️ 请自检并全部**勾选全部选项**。⚠️

feat:enable the left or right keyboard to switch image

---

README.md
assets/index.less
docs/examples/controlledWithGroup.tsx
docs/examples/placeholder.tsx
docs/examples/previewgroup.tsx
src/Preview.tsx
src/PreviewGroup.tsx
tests/__snapshots__/previewGroup.test.tsx.snap
tests/previewGroup.test.tsx

[[English Template / 英文模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)]
[Image 希望显示 current / total 浏览进度的标题](https://github.com/ant-design/ant-design/issues/35006)
| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |   preview group adds the title of the browsing progress at the top   |
| 🇨🇳 中文 |     PreviewGroup 添加顶部浏览进度的标识     |
⚠️ 请自检并全部**勾选全部选项**。⚠️

feature: add top progress when use PreviewGroup

---

src/Preview.tsx
tests/preview.test.tsx

Reset the image rotation and position on double click.
This idea comes from Plotly:
https://plotly.com/python/creating-and-updating-figures/
https://user-images.githubusercontent.com/17039389/164958731-34783f2e-55f2-4051-9ef2-860af0aaf77d.mov

Reset rotation and position on double click

---

src/Image.tsx
tests/basic.test.tsx

close https://github.com/ant-design/ant-design/issues/36680

fix: should hide preview mask when Image is hidden

---

README.md
src/Image.tsx
src/Preview.tsx
tests/preview.test.tsx

之前默认放大缩小的倍数是 1 倍，这样无论是鼠标滚轮操作或是点击按钮操作，放大缩小的时候感觉非常突兀。
这里增加 scaleOffset 属性，且默认设置为 0.5 倍，更加接近普通操作情况。

feat: add scaleOffset prop, set the default scaleOffset to 0.5

---

src/Preview.tsx
tests/__snapshots__/previewGroup.test.tsx.snap

我认为，正如这个[issue](https://github.com/ant-design/ant-design/issues/37243)所描述的那样，哪怕仅有 `PrviewGroup` 下仅有一个 `Image` 时，也应该可以看标题

fix: only one group item should have operation-process

---

assets/index.less
package.json
src/Preview.tsx
tests/__snapshots__/preview.test.tsx.snap

`operations`（操作条）在过渡动画运行中 `opacity`（透明度）不为 `1` 时，会被 fixed 定位且层级高的 dom 遮挡
https://user-images.githubusercontent.com/38420763/200565420-8f551967-ad31-46d6-9777-20432d2936ed.mov
以下代码可以复现上面的场景：
```html
<!DOCTYPE html>
<html lang="en">
<style>
div{
width: 100px;
height: 100px;
} 
#a {
background:red;
position: fixed;
top: 0;
z-index: 9999;
} 
#b {
background:blue;
position: fixed;
left: 20px;
top: 20px;
z-index: 9;
} 
#c {
background:green;
left: 40px;
top: 40px;
position: fixed;
z-index: 10;
} 
</style>
<body>
<div style="opacity: 0.9">
<div id="a">1-被遮挡</div> 
</div>
<div id="b">2</div> 
<div id="c">3</div> 
</body>
</html>
```

fix: operations are overridden when their opacity is not 1

---

package.json
src/Preview.tsx
tests/__snapshots__/preview.test.tsx.snap

`相册模式` 例子 `display: 'none'`  operations 会显示不出来

fix: operations are not displayed

---

src/previewConfig.ts
tests/preview.test.tsx

修复在 window 系统鼠标缩放过慢，鼠标滚动时 onWheel 事件 event.deltaY 的值在 widnows 与 mac 两个系统中存在差异
before：
onWheel 事件单次缩放比例最大限制 0.2 * scaleStep(0.5) = 0.1，在windows系统用鼠标 0.1 倍的缩放会导致很慢
after:
onWheel 事件单次缩放比例最大限制 1 * scaleStep(0.5) = 0.5，刚好是 scaleStep 的值，0.5 倍的缩放

fix: window system mouse zooming too slow

---

README.md
src/Preview.tsx
src/hooks/useImageTransform.ts
tests/preview.test.tsx

还是有这样的需求的
https://github.com/react-component/image/issues/192

feat: onTransform support action param

---

README.md
assets/index.less
docs/demo/imageRender.md
docs/examples/imageRender.tsx
src/Image.tsx
src/Operations.tsx
src/Preview.tsx
src/PreviewGroup.tsx
tests/preview.test.tsx
tests/previewGroup.test.tsx

https://github.com/ant-design/ant-design/issues/27273
https://github.com/ant-design/ant-design/issues/40279
使用 PreviewGroup 的情况下，现在的做法是使用 PreviewGroup 的 imgRender，暴露出 current。看下是否可行
```
<Image.PreviewGroup preview={{ imgRender: (originalNode, current) => ... }}>
<Image preview={{ imgRender: ... }} />   // 无效
<Image />
</Image.PreviewGroup>
```

feat: support imageRender

---

README.md
docs/demo/album.md
docs/examples/album.tsx
docs/examples/previewgroup.tsx
src/Image.tsx
src/PreviewGroup.tsx
tests/preview.test.tsx
tests/previewGroup.test.tsx

组件自身实现相册模式
代替 https://ant.design/components/image-cn#components-image-demo-preview-group-visible
隐藏 dom，用户自己用受控 visible 展示预览
```
<Image preview={{ only: true }} />
or
<Image.PreviewGroup preview={{ only: true }}>
....
</Image.PreviewGroup>
```
相册模式，用户自行决定外面显示哪个图片，只要这个图片不设置 only 即可。
```
<Image.PreviewGroup>
<Image />
<Image preview={{ only: true }} />
<Image preview={{ only: true }} />
</Image.PreviewGroup>
```

feat: showOnlyInPreview

---

src/Image.tsx
src/PreviewGroup.tsx
src/hooks/usePreviewItems.ts
tsconfig.json

1、优化打开预览时 index 判断，可减少渲染
2、只 pick items 的 ts 定义的那部分属性，保持一致。

fix: optimize preview setting index

---

tsconfig.json

fix https://github.com/react-component/image/pull/258/files#r1233237066
`prettier-plugin-sort-imports` 会移除非必要引入，作为组件库会 break 掉使用。例如创建一个 `tmp.tsx` 写以下代码：
```tsx
import React from 'react';
export default () => <></>;
```
当 tsconfig 设置 `"jsx": "preserve"` 后，会被 prettier 掉成：
```tsx
export default () => <></>;
```
编译后代码为：
```js
export default (function () {
return /*#__PURE__*/React.createElement(React.Fragment, null);
});
```
导致使用该库的用户报错 React 未定义，`tsconfig` 中设置 `"jsx": "react"` 即可。

chore: adjust tsconfig

---

src/Image.tsx
src/common.ts
src/hooks/usePreviewItems.ts

https://github.com/ant-design/ant-design/pull/42750
- (undefined) Circular dependency detected:
node_modules/rc-image/es/Image.js -> node_modules/rc-image/es/PreviewGroup.js -> node_modules/rc-image/es/hooks/usePreviewItems.js -> node_modules/rc-image/es/Image.js
- (undefined) Circular dependency detected:
node_modules/rc-image/es/PreviewGroup.js -> node_modules/rc-image/es/hooks/usePreviewItems.js -> node_modules/rc-image/es/Image.js -> node_modules/rc-image/es/PreviewGroup.js
- (undefined) Circular dependency detected:
node_modules/rc-image/es/hooks/usePreviewItems.js -> node_modules/rc-image/es/Image.js -> node_modules/rc-image/es/PreviewGroup.js -> node_modules/rc-image/es/hooks/usePreviewItems.js

refactor: solve image circular dependency issue

---

assets/index.less
docs/examples/album.tsx
docs/examples/basic.tsx
docs/examples/imageRender.tsx
docs/examples/previewgroup.tsx
src/Image.tsx

https://github.com/react-component/image/issues/263
isImageValid 是 https://github.com/react-component/image/pull/187 故意为之

fix: should not load preview src when mount

---

src/Operations.tsx
tests/preview.test.tsx

fix https://github.com/ant-design/ant-design/issues/43912
没点击 Portal 时，按下 esc 有效，因为是走的 rc-dialog 的 onClose（绑在 div 上），点击 Portal 后就无效了。于是给 Portal 单独绑定 esc

fix: should be closed when press esc after click portal

---

src/hooks/useStatus.ts
tests/fallback.test.tsx

fix https://github.com/ant-design/ant-design/issues/44948
fix https://github.com/react-component/image/issues/277

fix: should not trigger isImageValid.then when src changed

---

src/Operations.tsx
src/Preview.tsx
src/hooks/useImageTransform.ts
src/hooks/useMouseEvent.ts
src/hooks/useTouchEvent.ts
tests/previewTouch.test.tsx

图片预览移动端添加手势移动与缩放功能
close https://github.com/ant-design/ant-design/issues/44529

feat: added mobile touch event Interaction for Images

---

.gitignore
docs/examples/toolbarRender.tsx
src/Image.tsx
src/Operations.tsx
src/Preview.tsx

Related to https://github.com/ant-design/ant-design/issues/48713 , I passed the imgInfo as param to these two related functions.

feat: add imgInfo param for render function

---

docs/demo/previewgroup-items.md
docs/examples/controlledWithGroup.tsx
docs/examples/previewgroup-items.tsx
src/Image.tsx
src/PreviewGroup.tsx
src/hooks/usePreviewItems.ts
src/interface.ts
tests/previewGroup.test.tsx

* 修复 PreviewGroup#items 自定义时，默认定位到第 0 张的问题（因为查找按照自增 id 去查找了，此时应跳过查找）

fix: support PreviewGroup#items locating when clicking image

---

README.md
docs/examples/toolbarRender.tsx
src/Operations.tsx
src/Preview.tsx
src/hooks/useImageTransform.ts
tests/preview.test.tsx

- https://github.com/ant-design/ant-design/issues/48922

feat: support reset action in toolbarRender

---

.npmrc
src/Image.tsx
src/Preview.tsx
tests/preview.test.tsx

Fix the preview img size bug.
fix https://github.com/ant-design/ant-design/issues/49235
close #353

fix: fix the preview img size

---

README.md
src/Operations.tsx
src/Preview.tsx
tests/preview.test.tsx
tests/previewGroup.test.tsx

ref: [ant-design/ant-design#47948](https://github.com/ant-design/ant-design/issues/47948)

feat: add previous and next toggle to toolbar

---

src/Preview/index.tsx
tests/preview.test.tsx
tests/previewGroup.test.tsx

在 antd 侧文档没写，但是 demo 居然用了。防止 break change 补上 `afterOpenChange`

chore: add afterOpenChange
